### ISSUE TITLE
Migrate orion platforms to use nested config objects

### ISSUE THREAD

**Issue by jjm** [StackStorm-Exchange/stackstorm-orion#1]
We can move back to supporting multiple Orion platforms now that  _nested config objects_ support that was added in v2.1 of StackStorm.

This should hopefully be a easy and quick win!

**Comment by jjm** [comment]
This is a very old issue, I think it should most likely just get closed as I'm not got access to an Solarwinds Orion cluster to test any more.

CC: @nmaludy thoughts?

**Comment by nmaludy** [comment]
@jjm i think it's still probably valid although not useful to use in our current scenario.

probably close it until someone else needs it... also we're trying to move from SolarWinds to Prometheus... too many problems with SolarWinds.
