### ISSUE TITLE
New Maintainer required

### ISSUE THREAD

**Issue by jjm** [StackStorm-Exchange/stackstorm-orion#11]
Last month I changed jobs and I am now no longer working somewhere with access to Solarwinds Orion, so this pack needs a new maintainer.

**Comment by nmaludy** [comment]
Encore volunteers to taking over. Both me and Brad from Encore can work on it.

**Comment by jjm** [comment]
@nmaludy Cool 👍

**Comment by LindsayHill** [comment]
Resolved by #12 and by changes I've made to teams. @nmaludy let me know GH handles to add to @StackStorm-Exchange/encoretechnologies
